draft-test-func
HippoMaru/WordParser pull request #8
Opened 2024-04-11 16:06 UTC by SaintTonka

2024-04-11 16:22 UTC, HippoMaru requested changes
good job, завтра я возьмусь за свои)))

2024-04-11 16:22 UTC, HippoMaru commented on parser.py
> +    tree.getroot().append(section)
у тебя функция add_heaader_to_xml - её задача навесить хэдер на ET, который мы уже вырезали из основного дерева. вырезать ничего не нужно, грубо говоря переданный tree это уже и есть section. В общем - код не для этой функции

2024-04-11 16:22 UTC, HippoMaru commented on parser.py
> +    tree.getroot().append(section)
так понимаю, работа ведётся не  с копией дерева, а с ним самим. чистые функции python (и не только) не должны изменять состояние своих входных параметров, получил вход - выдал выход. ничто переданное на вход своего состояния менять не должно, за изменение состояний объектов отвечают методы их классов, для всего остального используется копирование и переприсваивание

2024-04-11 16:22 UTC, HippoMaru commented on parser.py
> +  return tree
изменился сам tree (что не круто, но энивэй если вдруг так делаем), соответственно возвращать его нет смысла, он всё по той же ссылке, что и была подана первым аргументом. опять же  хорошее решение в самом начале создать копию tree, работать с ней и в конце вернуть копию не затрагивая первоисточник

2024-04-12 08:28 UTC, SaintTonka commented
..... (¯`v´¯)♥
.......•.¸.•´
....¸.•´
... (
☻/
/▌♥♥
/ \ ♥♥

2024-04-23 18:28 UTC, HippoMaru commented
https://gist.github.com/HippoMaru/17d58afab4cd05c6b4e4903171b10354

2024-05-03 09:05 UTC, merged